#!/usr/bin/env bash
# SSL termination implementation

[ -x /usr/sbin/haproxy ] || apt-get update && apt-get install haproxy -y
[ -x /usr/bin/certbot ] || apt-get install certbot -y

source ./haproxy_cfg.sh # This sets $HA_CONF variable
service haproxy stop

pub=/etc/letsencrypt/live/anexe.tech/fullchain.pem
priv=/etc/letsencrypt/live/anexe.tech/privkey.pem
final_cert=/etc/letsencrypt/live/anexe.tech/merged.pem

# Incase I want to renew the certificate
if [ "$1" = "renew" ]; then
  certbot renew
  cat "$pub" "$priv" | tee "$final_cert" > /dev/null
  exit 0
fi

# Incase I wat to recreate the certificate
if [ "$1" = "recreate" ] && [ -f "$pub" ] ; then
  certbot delete --cert-name anexe.tech
fi

[ -f "$pub" ] && [ -f "$priv" ] || certbot certonly --standalone -n --agree-tos \
-m aneze.dev@gmail.com -d anexe.tech -d www.anexe.tech

cat "$pub" "$priv" | tee "$final_cert" > /dev/null

[ -f /etc/haproxy/haproxy_bak.cfg ] || \
cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy_bak.cfg

[ -f /etc/letsencrypt/live/anexe.tech/dhparam.pem ] || \
openssl dhparam -out /etc/letsencrypt/live/anexe.tech/dhparam.pem 2048
echo "$HA_CONF" | tee /etc/haproxy/haproxy.cfg > /dev/null
service haproxy restart

