#!/usr/bin/env bash
# SSL termination implementation
apt-get update
[ -x /usr/sbin/haproxy ] || apt-get install haproxy -y
[ -x /usr/bin/certbot ] || apt-get install certbot -y

source ./haproxy_cfg.sh # This sets $HA_CONF variable
service haproxy stop

pub=/etc/letsencrypt/live/anexe.tech/fullchain.pem
priv=/etc/letsencrypt/live/anexe.tech/privkey.pem
final_cert=/etc/letsencrypt/live/anexe.tech/merged.pem
[ -f "$final_cert" ] || certbot certonly --standalone -n --agree-tos \
-m aneze.dev@gmail.com -d anexe.tech -d anexe.ddns.net

cat "$pub" "$priv" | tee "$final_cert" > /dev/null

[ -f /etc/haproxy/haproxy_bak.cfg ] || \
cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy_bak.cfg

[ -f /etc/letsencrypt/live/anexe.tech/dhparam.pem ] || \
openssl dhparam -out /etc/letsencrypt/live/anexe.tech/dhparam.pem 2048
echo "$HA_CONF" | tee /etc/haproxy/haproxy.cfg > /dev/null
service haproxy restart

