#!/usr/bin/env bash
# Install nginx inserver and change to the the nginx root
# Script to be executed with sudo privileges
apt-get update
apt-get install nginx -y

# Create the default content: "Hellow world!"
ROOT=/var/www
mkdir -p $ROOT/html
helloworld="<html> <body> Hello World! </body> </html>"
echo $helloworld | tee $ROOT/html/index.html > /dev/null

service nginx restart
curl 0.0.0.0:80
