#!/usr/bin/env bash
# Install nginx inserver and change to the the nginx root
# Script to be executed with sudo privileges
apt-get update
apt-get install nginx -y

# Create the default content: "Hellow world!"
ROOT=/var/www
mkdir -p $ROOT/html
helloworld="<html> <body> Hello World! </body> </html>"
echo "$helloworld" | tee "$ROOT/html/index.html" > /dev/null

service nginx restart
# curl 0.0.0.0:80

# --------------Redirect--------------------
sudo mkdir -p /var/www/site.url/nginx
# Replace the whole contents of "/etc/nginx/sites-enabled/default" with below
contents=$(cat <<"END"
server {
	listen 80 default_server;
	listen [::]:80 default_server;
	root /var/www/html;
	index index.html index.htm index.nginx-debian.html;
	server_name _;
	location / {
		try_files $uri $uri/ =404;
	}
	# Add Redirects HERE
	location /redirect_me {
		return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
	}
}

END
)

echo "$contents" | tee /etc/nginx/sites-enabled/default > /dev/null
# nginx -t
service nginx restart
