#!/usr/bin/env bash
# Restore Nginx sites-enabled from sites-available since the link is broken
rm /etc/nginx/sites-enabled/default
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
/etc/init.d/nginx restart  # Restart Nginx using service command
