#!/usr/bin/env bash
# Indefinitley writes 'I am alive!' to tmp/my_process

pid_f="/var/run/my_process.pid"

function create_pid_f()
{
	proc_id="$1"
	touch "$pid_f"
	if [ -e "$pid_f" ]; then
		echo "$proc_id" | sudo tee "$pid_f"
		echo "manage_my_process started"
	fi
}

# Create the log file if missing
if [ ! -f tmp/my_process ]; then
		mkdir tmp
		touch tmp/my_process
fi

# The logger machine
while true; do
	if [ -e "$pid_f" ]; then # does the pid file exist?
		echo "I am alive!" >> tmp/my_process
		sleep 2
	else
		create_pid_f $$ # create the pid file only once
	fi
done

