#!/usr/bin/env bash
# Indefinitley writes 'I am alive!' to tmp/my_process

STARTED=0
# The pid file
pid_f="/var/run/my_process.pid"

# create the pid file
function create_pid_f()
{
	proc_id="$1"
	# status: {started|restarted}
	status="$2"
	touch "$pid_f"
	# echo "$proc_id" | sudo tee "$pid_f" > /dev/null 2>&1
	echo "$proc_id" | sudo tee "$pid_f" > /dev/null
	echo "manage_my_process $status"
}

# Quit if process is already running
# if [ -f "$pid_f" ]; then exit 0; fi

# Create the log file if missing
if [ ! -f tmp/my_process ]; then
		mkdir tmp
		touch tmp/my_process
fi

# The logger machine
while true; do
	if (( $STARTED == 1 )); then # No Infinity infinity?
		echo "I am alive!" >> tmp/my_process
		sleep 2
	else
	# status: {started|restarted}
		status="$1"
		STARTED=1
		create_pid_f $$ "$status" # create the pid file only once
	fi
done

