#!/usr/bin/env bash
# Bash script that displays the content of the file /etc/passwd
# Your script should only display:
# 	username, user id, and the Home directory path for the user
f="/etc/passwd"

if [ -e "$f" ]; then
	# open for reading only
	exec 3<"$f"
	# Read f line by line
	while read -r line <&3; do
		echo "$line" | cut -d":" -f1,4,6
	done
	# close f
	3<&-

fi
