#!/usr/bin/env bash
# Bash script that displays numbers from 1 to 20 and:
# 	displays 4 and then bad luck from China for the 4th loop iteration
#		displays 9 and then bad luck from Japan for the 9th loop iteration
# 	displays 17 and then bad luck from Italy for the 17th loop iteration
i=0
while ((i < 20)); do
	echo $((i+1))
	if (( i == 3 )); then echo "bad luck from China"; fi
	if (( i == 8 )); then echo "bad luck from Japan"; fi
	if (( i == 16 )); then echo "bad luck from Italy"; fi

	((i++))
done
