#!/usr/bin/env bash
# Bash script that displays:
# The content of the current directory
# Where only the part of the name after the first dash is displayed

for i in *; do
	echo "$i" | cut -d"-" -f2-;
	# cut -delim "-", select from -field2 till end of string
done
