#!/usr/bin/env bash
# Configures port forwarding

#!/usr/bin/env bash

if ! command -v ufw > /dev/null 2>&1;
	then
		apt update && apt install ufw -y
	fi

if ! systemctl is-enabled ufw > /dev/null 2>&1;
	then
	systemctl enable ufw
	fi

# Ensure ufw is in a disabled state
ufw disable

# Allow all out going
ufw default allow outgoing

# Deny all incoming
ufw default deny incoming

# Allow incoming ssh (22/tcp)
ufw allow 22/tcp

# Allow HTTPS
ufw allow 443/tcp

# Allow HTTP
ufw allow 80/tcp

# Specifically allow the load balancer ip address in case all web traffic is blocked
ufw allow from 54.88.115.160 to any port 80 proto tcp
# Enable ufw
ufw enable

# check status
# ufw status


# ufw status mnumbered
# ufw delete 1 - rule number 1
# ufw delete 1 - rule number 3 The ipv6 of same
# Port 80 from anywhere is good
# port 22 from only your internet connection to allow you test but should
# blocked to others to limit attack surfce

sudo iptables -t nat -A PREROUTING -p tcp --dport 8080 -j REDIRECT --to-port 80
