#!/usr/bin/env bash
# Run the given command as another user
# Check if the user name is provided
USER=$1
if [ -z "$USER" ]; then
	echo "Please provide a username."
	exit 1
fi

# Check if the user exists in the system
if ! id "$USER" >& /dev/null; then
	echo "User '$USER' does not exits."
	exit 1
fi

sudo -u "$USER" whoami # $USER is not privileged
exit 0
